### ISSUE TITLE
Grade book display issues

### ISSUE THREAD

**Issue by martygilbert** [eduridden/moodle-theme_essential#45]
It seems there's a lot of wasted space in the grade book display, particularly when viewing the 'Simple view' of 'Categories and items'. So much, in fact, that a scroll bar has to be added in order to modify any of the categories or items.

Screenshot 1 - The top display of the simple view. 
![screenshot from 2013-08-10 12 07 18](https://f.cloud.github.com/assets/616253/942829/2ddef4aa-01d7-11e3-8fe6-48f186466e50.png)

Screenshot 2 - The bottom of the long list of grades + scroll bar in frame
![screenshot from 2013-08-10 12 07 31](https://f.cloud.github.com/assets/616253/942827/2dd790f2-01d7-11e3-86ad-1ec70e436773.png)

Screenshot 3 - The bottom of the grade list, scrolled to the right.
![screenshot from 2013-08-10 12 08 46](https://f.cloud.github.com/assets/616253/942828/2dd76c3a-01d7-11e3-9da2-9540b83a99f9.png)

I'm not sure if this is a theme issue, but I thought I would raise the issue in case there was something that could be done within Essential in order to make it easier to add/edit grade categories.

Thanks again for all of your hard work.

**Comment by martygilbert** [comment]
Testing this, it works in ESSENTIAL_254, version 2013082700

**Comment by kimboking** [comment]
Having this issue in Essential 2.6 running on Moodle 2.5.2 (see attached screenshot).  Cannot upgrade to Moodle 2.6 and Essential 2.6.2 just yet.  

Can this fix be applied to Essential 2.6 so that the entire gradebook edit table appears on one page as shown here:  http://s5.postimg.org/kvogji52f/Gradebook_Should_Be.jpg?

![essential edit gradebook layout difficult to navigate](https://f.cloud.github.com/assets/6333407/1853733/4fe556ca-7711-11e3-8acd-a3feff532b57.jpg)
